version: '3.8'

services:
  postgres:
    image: postgres:14.0
    ports:
      - '5432:5432'
    restart: always
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: db
